### ISSUE TITLE
Doesn't support nested yaml feature

### ISSUE THREAD

**Issue by pjaspers** [pjaspers/dumper#1]
```
default: &default
  adapter: postgresql
  pool: 5
  username: roundabout
  min_messages: WARNING
  timeout: 5000

development:
  <<: *default
  database: roundabout_dev
```

Doesn't work.
